CVEAlert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('account/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('login/', views.get_login, name='login'),
    path('sign-up/', views.get_sign_up, name='sign_up'),
    path('log-out/', views.get_logout, name='log_out'),
    path('profile/', views.profile_detail_view, name='profile'),
    path('change-password', views.change_password_view, name='change_password'),
    path('list-affect', views.list_affect_view, name='list_affect'),
	path('notification/', views.notification_user_view, name='notification'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
	dob = models.CharField(blank=True, max_length=225)
	phone_number = models.CharField(max_length=225, blank=True)
	full_name = models.CharField(max_length=225, blank=True)
	email_profile = models.CharField(max_length=225, blank=True)

	def __str__(self):
		return str(self.user.username)
	
class NotiUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_notification')
	status = models.CharField(max_length=225, blank=True)
	email_address = models.EmailField(blank=True)
	token_bot = models.CharField(max_length=225, blank=True)
	chat_id = models.CharField(max_length=225, blank=True)

	def __str__(self):
		return str(self.user.username)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, NotiUser

class UserProfileSignUpForm(UserCreationForm):
	email = forms.EmailField(required=True, label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email'}))
	username = forms.CharField(required=True, label='Username',
							   widget=forms.TextInput(attrs={'placeholder': 'Username'}))
	password1 = forms.CharField(required=True, label='Password',
								widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
	password2 = forms.CharField(required=True, label='Confirm Password',
								widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

	class Meta:
		model = User
		fields = (
			'username',
			'email',
			'password1',
			'password2',
		)

class EditProfile(forms.ModelForm):
	class Meta:
			model = UserProfile
			fields = (
				'full_name',
				'dob',
				'phone_number',
				'email_profile'
			)

class CreateNotification(forms.ModelForm):

	class Meta:
		model = NotiUser
		fields = '__all__'

accounts/views.py
from django.contrib.auth import login, authenticate , logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse




from . import forms
from . import models

# Create your views here.

def get_login(request):
	form = AuthenticationForm()
	msg = ""
	
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')

			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return HttpResponseRedirect(reverse('app:home'))
			else:
				msg = "Your account name or password is incorrect!"
		else:
			msg = "Your account name or password is incorrect!"
			
	context = {
		'form': form,
		'msg': msg
	}
	return render(request, 'accounts/login.html', context=context)


def get_sign_up(request):
	form = forms.UserProfileSignUpForm()
	
	if request.method == 'POST':
		form = forms.UserProfileSignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			create_profile = models.UserProfile.objects.create(user=user)
			create_profile.save()
			return HttpResponseRedirect(reverse('app:home'))
		
	return render(request, 'accounts/sign_up.html', {'form': form})

@login_required
def get_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('app:home'))

@login_required
def profile_detail_view(request):
	profile = models.UserProfile.objects.get(user=request.user)
	form = forms.EditProfile()
	profile = models.UserProfile.objects.get(user=request.user)
	if request.method == 'POST':
		form = forms.EditProfile(request.POST or None, request.FILES, instance=profile)
		if form.is_valid():
			form.save(commit=True)
			return HttpResponseRedirect(reverse('accounts:profile'))
	
	context= {
		'profile' : profile,
		'form' :form,
	}

	return render(request,'accounts/profile.html',context=context)





def list_affect_view(request):
	return render(request, 'accounts/list_affect.html')

@login_required
def change_password_view(request,pk):
	mess = ""
	if request.method == 'POST' and 'your_new_password1' in request.POST:
		cur_user = models.User.objects.get(pk=pk)
		old_pass = request.POST['old_password']
		new_pass = request.POST['new_pass']
		new_pass_conf = request.POST['new pass1']
		print("--check", cur_user.check_password(old_pass))
		if not cur_user.check_password(old_pass):
			mess = "wrong old password , please try again!"
		elif new_pass != new_pass_conf :
			mess = "new password u input is not identical , please try again!"
		else:
			cur_user.set_password(new_pass)
			cur_user.save
			mess = "u have changed password succesfully"
			return HttpResponseRedirect(reverse('app:home'))
		
	context = {
		'mess' : mess
	}
	return render(request, 'accounts/change_password.html', context=context)

def notification_user_view(request):
	return render(request, 'accounts/notification_user.html')

templates/accounts/change_pasword.html
{% extends 'navbar.html' %}


{% block css %}
    .form-change-pass > input {
    width: 100%;
    margin-bottom: 20px;
    border-radius: 5px;
    }
    .form-change-pass > button {
    width: 50%;
    }
    .list-page-profile > p > a {
    color: black;
    text-decoration: none;
    font-weight: bold;
    }
    .list-page-profile > p > .active {
    color: dodgerblue;
    }
    body {
    background-color: white !important;
    }
    .alert-msg {
        background-color: #f76f6f;
        color: white;
        padding: 10px;
        border-radius: 5px;
        border-color: blue;
    }
{% endblock %}


{% block title %}
    Change Password
{% endblock %}


{% block content %}
<div class="container" style="padding: 20px;">
    <div class="row">
        <div class="col-4 list-page-profile">
            <p>
                <a href="{% url 'accounts:profile' %}">Personal Info</a>
            </p>
            <p>
                <a class="active" href="{% url 'accounts:change_password' pk=request.user.pk %}">Password</a>
            </p>
            <p>
                <a href="{% url 'accounts:list_affect' page=1 %}">Affected Followed</a>
            </p>
            <p>
                <a href="{% url 'accounts:notification' %}">Setting Notification</a>
            </p>
        </div>
        <div class="col-6">
            <h2>Change Password</h2>
            <form method="post" class="form-change-pass">
                {% csrf_token %}
                <label for="old_password">
                    Old Password
                </label>
                <input type="password" name="old_password" id="old_password"/><br>
                <label for="password1">
                    New Password
                </label>
                <input type="password" name="your_news_password1" id="password1"/><br>
                <label for="password2">
                    Confirm Password
                </label>
                <input type="password" name="your_news_password2" id="password2"/><br>
                <button type="submit" class="btn btn-primary">SAVE</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/list_affect.html
{% extends 'navbar.html' %}


{% block css %}

{% endblock %}


{% block title %}
    abcxyz
{% endblock %}


{% block content %}

{% endblock %}

templates/accounts/login.html
{% extends 'navbar.html' %}


{% block css %}
    body {
    background-color: #2b2426 !important;
    }
    input, button {
    width: 100%;
    }
    .form-login {
    width: 60%;
    border: 1px solid #ccc;
    padding: 50px;
    background-color: white;
    padding: 25px;
    border-radius: 5px;
    line-height: 30px;
    margin-top: -410px;
    margin-bottom: 50px;
    z-index: 99;
    position:relative;
    }
    .form-login > form > * {
    margin-bottom: 20px;
    border-radius: 5px;
    }
    .alert-msg {
        background-color: #f76f6f;
        color: white;
        padding: 10px;
        border-radius: 5px;
        border-color: red;
    }
    /*=Login=*/
.btn {
    line-height: 15px;
    height: 40px;
    text-align: center;
    text-style:bold
    width: 120px;
    cursor: pointer;
    background-color:black;
  }
  .btn-one {
    color: white;
    transition: all 0.5s;
    position: relative;
  }
  .btn-one span {
    transition: all 0.5s;
  }
  .btn-one::before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 2;
    opacity: 0;
    transition: all 1s;
    border-top-width: 1px;
    border-bottom-width: 1px;
    border-top-style: solid;
    border-bottom-style: solid;
    border-top-color: black;
    border-bottom-color: black;
    transform: scale(0.1, 1);
    
  }
  .btn-one:hover span {
    letter-spacing: 2px;
  }
  .btn-one:hover::before {
    opacity: 1; 
    transform: scale(1, 1); 
  }
  .btn-one::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    transition: all 0.3s;
    background-color: rgba(255,255,255,0.1);
  }
  .btn-one:hover::after {
    opacity: 0; 
    transform: scale(0.1, 1);
  }

  /*=continuew with Google=*/
  .btn2 {
      line-height: 15px;
      height: 40px;
      text-align: center;
      text-style:bold
      width: 120px;
      cursor: pointer;
      background-color:white;
      
    }
    .btn2-two {
      color: white;
      transition: all 0.5s;
      position: relative;
    }
    .btn2-two span {
      transition: all 0.5s;
    }
    .btn2-two::before {
      content: '';
      position: absolute;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 2;
      opacity: 0;
      transition: all 1s;
      border-top-width: 1px;
      border-bottom-width: 1px;
      border-top-style: solid;
      border-bottom-style: solid;
      border-top-color: black;
      border-bottom-color: black;
      transform: scale(0.1, 1);
    }
    .btn2-two:hover span {
      letter-spacing: 2px;
    }
    .btn2-two:hover::before {
      opacity: 1; 
      transform: scale(1, 1); 
    }
    .btn2-two::after {
      content: '';
      position: absolute;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 1;
      transition: all 0.3s;
      background-color: rgba(255,255,255,0.1);
    }
    .btn2-two:hover::after {
      opacity: 0; 
      transform: scale(0.1, 1);
    
    }
{% endblock %}


{% block title %}
    Login
{% endblock %}


{% block content %}
<img src="/media/hinh-nen-may-tinh-den-trang-soc-ke_022909111.jpg" style="width: 100%; height:700px;" alt="background">
<div class="container form-login">
    <div class="row">
        <div class="col">
            <h2><b>LOGIN</b></h2>
        </div>
        <div class="col">
            <p style="float: right;">Don't have an account? <a href="{% url 'accounts:sign_up' %}"><b
                    style="background-color: black; color: white; padding: 5px; font-size: 10px;">JOIN NOW</b></a>
            </p>
        </div>
    </div>
    {% if msg %} 
    <p class="alert-msg">{{ msg }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="User name">
        <input type="password" name="password" id="password" placeholder="Password">
        <button type="submit" class="btn btn-one"  ><b>LOGIN </b></button>
        <button class="btn2 btn2-two" style="color:black;"><b>Countinue with Google</b></button>
        
    </form>
</div>
{% endblock %}

templates/accounts/notification_user.html
{% extends 'navbar.html' %}

{% block css %}
    .form-edit-profile > input {
    width: 100%;
    margin-bottom: 20px;
    border-radius: 5px;
    }
    .form-edit-profile > button {
    width: 50%;
    }
    body {
    background-color: white !important;
    }
    input, select, textarea {
    width: 100%;
    border-radius: 5px;
    margin-bottom: 10px;
    padding: 5px;
    }
    .form-edit-avatar {
    text-align: center;
    }
    .list-page-profile > p > a {
    color: black;
    text-decoration: none;
    font-weight: bold;
    }
    .list-page-profile > p > .active {
    color: dodgerblue;
    }

    /*=Link=*/
    .link{
        a {
            box-shadow: inset 0 0 0 0 black;
            color: black;
              padding: 0 .25rem;
              margin: 0 -.25rem;
              border-radius: 5px;
            transition: color .5s ease-in-out, box-shadow .5s ease-in-out;
          }
          a:hover {
            color: white;
            box-shadow: inset 200px 0 0 0 black;;
          }
          
          /* Presentational styles */
          a {
            color: black;
            font-size: 18px;
            font-weight: 600;
            line-height: 0;
            text-decoration: none;
          }
    }
    
    /*=SAVE=*/
.btn {
    line-height: 20px;
    height: 50px;
    text-align: center;
    text-style:bold
    cursor: pointer;
    background-color:dodgerblue;
  }
  .btn-one {
    color: white;
    transition: all 0.5s;
    position: relative;
  }
  .btn-one span {
    transition: all 0.5s;
  }
  .btn-one::before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 2;
    opacity: 0;
    transition: all 1s;
    border-top-width: 1px;
    border-bottom-width: 1px;
    border-top-style: solid;
    border-bottom-style: solid;
    border-top-color: dodgerblue;
    border-bottom-color: dodgerblue;
    transform: scale(0.1, 1);
    
  }
  .btn-one:hover span {
    letter-spacing: 2px;
  }
  .btn-one:hover::before {
    opacity: 1; 
    transform: scale(1, 1); 
  }
  .btn-one::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    transition: all 0.3s;
    background-color: rgba(255,255,255,0.1);
  }
  .btn-one:hover::after {
    opacity: 0; 
    transform: scale(0.1, 1);
  }
{% endblock %}

{% block title %}
    Setting Notification
{% endblock %}


{% block content %}
    <div class="container" style="padding: 70px;">
        <div class="row">
            <div class="col-4 list-page-profile">
                <p class="link">
                    <a href="{% url 'accounts:profile' %}">Personal Info</a>
                </p>
                <p class="link">
                    <a href="{% url 'accounts:change_password'%}">Password</a>
                </p>
                <p class="link">
                    <a href="{% url 'accounts:list_affect'%}">Affected Followed</a>
                </p>
                <p class="link">
                    <a class="active" href="{% url 'accounts:notification' %}">Setting Notification</a>
                </p>
            </div>
            <div class="col-6">
                <form method="post" class="form-edit-profile" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2><b>YOUR</b> <b style="color: dodgerblue">NOTIFICATION</b></h2>
                    <label for="status">Status</label>
                    <select name="status" id="status">
                            <option value=1></option>
                    </select>
                    <label for="email_address">Email Address</label>
                    <input type="email" name="email_address" id="email_address">
                    <label for="token_bot">Token Bot</label>
                    <input type="text" name="token_bot" id="token_bot" >
                    <label for="chat_id">Chat ID</label>
                    <input type="text" name="chat_id" id="chat_id">
                    <button type="submit" class="btn btn-one" style="width:100px"><b>SAVE</b></button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'navbar.html' %}

{% block css %}
    .form-edit-profile > input {
    width: 100%;
    margin-bottom: 20px;
    border-radius: 5px;
    }
    .form-edit-profile > button {
    width: 50%;
    }
    body {
    background-color: white !important;
    }
    .form-edit-avatar {
    text-align: center;
    }
    .list-page-profile > p > a {
    color: black;
    text-decoration: none;
    font-weight: bold;
    }
    .list-page-profile > p > .active {
    color: dodgerblue;
    }
    /*=Link=*/
    .link{
        a {
            box-shadow: inset 0 0 0 0 black;
            color: black;
              padding: 0 .25rem;
              margin: 0 -.25rem;
              border-radius: 5px;
            transition: color .5s ease-in-out, box-shadow .5s ease-in-out;
          }
          a:hover {
            color: white;
            box-shadow: inset 200px 0 0 0 black;;
          }
          
          /* Presentational styles */
          a {
            color: black;
            font-size: 18px;
            font-weight: 600;
            line-height: 0;
            text-decoration: none;
          }
    }
    
    /*=SAVE=*/
.btn {
    line-height: 20px;
    height: 50px;
    text-align: center;
    text-style:bold
    cursor: pointer;
    background-color:dodgerblue;
  }
  .btn-one {
    color: white;
    transition: all 0.5s;
    position: relative;
  }
  .btn-one span {
    transition: all 0.5s;
  }
  .btn-one::before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 2;
    opacity: 0;
    transition: all 1s;
    border-top-width: 1px;
    border-bottom-width: 1px;
    border-top-style: solid;
    border-bottom-style: solid;
    border-top-color: dodgerblue;
    border-bottom-color: dodgerblue;
    transform: scale(0.1, 1);
    
  }
  .btn-one:hover span {
    letter-spacing: 2px;
  }
  .btn-one:hover::before {
    opacity: 1; 
    transform: scale(1, 1); 
  }
  .btn-one::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    transition: all 0.3s;
    background-color: rgba(255,255,255,0.1);
  }
  .btn-one:hover::after {
    opacity: 0; 
    transform: scale(0.1, 1);
  }
{% endblock %}

{% block title %}
    Profile of {{ profile.user.username }}
{% endblock %}


{% block content %}
    <div class="container" style="padding: 70px;">
        <div class="row">
            <div class="col-4 list-page-profile">
                <p class = "link">
                    <a class="{% if '/account/profile/' == request.path %}active{% endif %}"
                       href="{% url 'accounts:profile' %}">Personal Info</a>
                </p>
                <p class = "link">
                    <a href="{% url 'accounts:change_password' %}">Password</a>
                </p >
                <p class = "link">
                    <a href="{% url 'accounts:list_affect' %}">Affected Followed</a>
                </p >
                <p class = "link">
                    <a href="{% url 'accounts:notification' %}">Setting Notification</a>
                </p>
            </div>
            <div class="col-6">
                <form method="post" class="form-edit-profile" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2><b>YOUR</b> <b style="color: dodgerblue">INFORMATION</b></h2>
                    <label for="id_full_name">Full name:</label>
                    <input type="text" name="full_name" maxlength="40" id="id_full_name" value="{{ profile.full_name }}">
                    <label for="id_dob">Dob:</label>
                    <input type="text" name="dob" maxlength="50" id="id_dob" value="{{ profile.dob }}">
                    <label for="id_phone_number">Phone number:</label>
                    <input type="text" name="phone_number" maxlength="20" id="id_phone_number" value="{{ profile.phone_number }}">
                    <label for="id_email_profile">Email profile:</label>
                    <input type="email" name="email_profile" maxlength="100" id="id_email_profile" value="{{ profile.email_profile }}">
                    <button type="submit" class="btn btn-one" style="width:100px"><b>SAVE</b></button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/sign_up.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}

{% block css %}
    body {
        background-color: #2b2426 !important;
    }
    input, button {
        width: 100%;
    }
    .form-login {
    width: 60%;
    border: 1px solid #ccc;
    padding: 50px;
    background-color: white;
    padding: 15px;
    border-radius: 5px;
    line-height: 30px;
    margin-top: -590px;
    margin-bottom: -12px;
    z-index: 99;
    position:relative;
    }
    .form-login > form > * {
    margin-bottom: 20px;
    border-radius: 5px;
    }

    /*=SignUp=*/
    .btn {
        line-height: 15px;
        height: 40px;
        text-align: center;
        text-style:bold
        width: 120px;
        cursor: pointer;
        background-color:black;
      }
      .btn-one {
        color: white;
        transition: all 0.5s;
        position: relative;
      }
      .btn-one span {
        transition: all 0.5s;
      }
      .btn-one::before {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 2;
        opacity: 0;
        transition: all 1s;
        border-top-width: 1px;
        border-bottom-width: 1px;
        border-top-style: solid;
        border-bottom-style: solid;
        border-top-color: black;
        border-bottom-color: black;
        transform: scale(0.1, 1);
        
      }
      .btn-one:hover span {
        letter-spacing: 2px;
      }
      .btn-one:hover::before {
        opacity: 1; 
        transform: scale(1, 1); 
      }
      .btn-one::after {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        transition: all 0.3s;
        background-color: rgba(255,255,255,0.1);
      }
      .btn-one:hover::after {
        opacity: 0; 
        transform: scale(0.1, 1);
      }
    
      /*=continuew with Google=*/
      .btn2 {
          line-height: 15px;
          height: 40px;
          text-align: center;
          text-style:bold
          width: 120px;
          cursor: pointer;
          background-color:white;
          
        }
        .btn2-two {
          color: white;
          transition: all 0.5s;
          position: relative;
        }
        .btn2-two span {
          transition: all 0.5s;
        }
        .btn2-two::before {
          content: '';
          position: absolute;
          bottom: 0;
          left: 0;
          width: 100%;
          height: 100%;
          z-index: 2;
          opacity: 0;
          transition: all 1s;
          border-top-width: 1px;
          border-bottom-width: 1px;
          border-top-style: solid;
          border-bottom-style: solid;
          border-top-color: black;
          border-bottom-color: black;
          transform: scale(0.1, 1);
        }
        .btn2-two:hover span {
          letter-spacing: 2px;
        }
        .btn2-two:hover::before {
          opacity: 1; 
          transform: scale(1, 1); 
        }
        .btn2-two::after {
          content: '';
          position: absolute;
          bottom: 0;
          left: 0;
          width: 100%;
          height: 100%;
          z-index: 1;
          transition: all 0.3s;
          background-color: rgba(255,255,255,0.1);
        }
        .btn2-two:hover::after {
          opacity: 0; 
          transform: scale(0.1, 1);
        
        }
{% endblock %}


{% block title %}
    Sign Up
{% endblock %}


{% block content %}
    <img src="/media/hinh-nen-may-tinh-den-trang-soc-ke_022909111.jpg" style="width: 100%; height:800px;" alt="background">
    <div class="container form-login">
        <div class="row">
            <div class="col">
                <h2><b>SIGN UP</b></h2>
            </div>
            <div class="col">
                <p style="float: right">Already have an account? <a href="{% url 'accounts:login' %}"><b style="background-color: black; color: white; padding: 5px; font-size: 10px;">LOGIN HERE</b></a></p>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-one" style="width: 100%">SIGN UP</button>
            <button class="btn2 btn2-two" style="color: black">Countinue with Google</button>
        </form>
    </div>
{% endblock %}