CVEAlert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('account/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('login/', views.get_login, name='login'),
    path('sign-up/', views.get_sign_up, name='sign_up'),
    path('log-out/', views.get_logout, name='log_out'),
    path('profile/', views.profile_detail_view, name='profile'),
    path('change-password', views.change_password_view, name='change_password'),
    path('list-affect', views.list_affect_view, name='list_affect'),
	path('notification/', views.notification_user_view, name='notification'),
]

firstapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import get_home, get_list_CVE,get_detail_cves,get_tele_notifi,get_gmail_notifi,create_cve_view,create_affect_view

app_name = 'app'

urlpatterns = [
    path('', get_home,name='home'),
    path('list-cve/<int:page>/', get_list_CVE,name='list_cves'),
    path('detail-cve/<int:pk>', get_detail_cves, name='detail_cves'),
    path('create-cve/', create_cve_view, name = 'create_cve'),
    path('create-affected/', create_affect_view, name = 'create_affected'),
    path('telegram-notification/', get_tele_notifi, name='tele_noti'),
	path('gmail-notification/', get_gmail_notifi, name='gmail_noti')
]

templates/gmail_notifi.html
{% extends 'navbar.html' %}


{% block css %}
    a {
    text-decoration: nobe;
    color: black;
    }
    input, textarea {
    width: 100%;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 10px;
    }
    .box-info {
    margin-bottom: 20px;
    margin-top: 20px;
    }
    .title-box > *{
    padding: 10px;
    background-color: black !important;
    color: white !important;
    border-top-right-radius: 10px !important;
    border-top-left-radius: 10px !important;
    margin: 0;
    }
    .content-box {
    background-color: lightgray !important;
    border-bottom-right-radius: 10px;
    border-bottom-left-radius: 10px;
    margin: 0;
    padding: 10px;
    }
    .alert-msg {
        background-color: lightgreen;
        color: black;
        padding: 10px;
        border-radius: 5px;
        border-color: red;
    }



    /*=READ NOW=*/
    .btn {
        line-height: 20px;
        height: 50px;
        text-align: center;
        text-style:bold
        cursor: pointer;
        background-color:black;
      }
      .btn-one {
        color: white;
        transition: all 0.5s;
        position: relative;
      }
      .btn-one span {
        transition: all 0.5s;
      }
      .btn-one::before {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 2;
        opacity: 0;
        transition: all 1s;
        border-top-width: 1px;
        border-bottom-width: 1px;
        border-top-style: solid;
        border-bottom-style: solid;
        border-top-color: black;
        border-bottom-color: black;
        transform: scale(0.1, 1);
        
      }
      .btn-one:hover span {
        letter-spacing: 2px;
      }
      .btn-one:hover::before {
        opacity: 1; 
        transform: scale(1, 1); 
      }
      .btn-one::after {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        transition: all 0.3s;
        background-color: rgba(255,255,255,0.1);
      }
      .btn-one:hover::after {
        opacity: 0; 
        transform: scale(0.1, 1);
      }
      /*=Link list=*/
      .list{
          a {
              box-shadow: inset 0 0 0 0 black;
              color: black;
                padding: 0 .25rem;
                margin: 0 -.25rem;
                left:10%;
                border-radius: 5px;
              transition: color .5s ease-in-out, box-shadow .5s ease-in-out;
            }
            a:hover {
              color: white;
              box-shadow: inset 200px 0 0 0 black;;
            }
            
            /* Presentational styles */
            a {
              color: black;
              font-size: 19px;
              font-weight: 500;
              line-height: 0;
              text-decoration: none;
            }
      }
    
    
    
      /*=arrow=*/
    .arrow {
        position: absolute;
        top: 19%;
        left: 14%;
        transform: translate(-50%, -50%);
        transform: rotate(90deg);
        cursor: pointer;
    }
    
    .arrow span {
        display: block;
        width: 1vw;
        height: 1vw;
        border-bottom: 5px solid black;
        border-right: 5px solid black;
        transform: rotate(45deg);
        margin: -10px;
        animation: animate 2s infinite;
    }
    
    .arrow span:nth-child(2) {
        animation-delay: -0.2s;
    }
    
    .arrow span:nth-child(3) {
        animation-delay: -0.4s;
    }
    
    @keyframes animate {
        0% {
            opacity: 0;
            transform: rotate(45deg) translate(-20px, -20px);
        }
        50% {
            opacity: 1;
        }
        100% {
            opacity: 0;
            transform: rotate(45deg) translate(20px, 20px);
        }
    }

    /*=CARD TITLE1=*/
  .card-title1{
      a {
          box-shadow: inset 0 0 0 0 black;
          color: black;
            padding: 0 .25rem;
            margin: 0 -.25rem;
            border-radius: 5px;
          transition: color .5s ease-in-out, box-shadow .5s ease-in-out;
        }
        a:hover {
          color: white;
          box-shadow: inset 200px 0 0 0 black;;
        }
        
        /* Presentational styles */
        a {
          color: black;
          font-family: 'Poppins', sans-serif;
          font-size: 23px;
          font-weight: 600;
          line-height: 0;
          text-decoration: none;
        }
  }

{% endblock %}


{% block title %}
    Gmail notification
{% endblock %}


{% block content %}
<div class="container" style="margin-top: 100px; margin-bottom: 200px">
    <p class="list"><a href={% url 'app:home' %}>RETURN HOME</a></p>
<div class="arrow">
    <span></span>
    <span></span>
    <span></span>
</div>
        <div class="row">
            <div class="col-8">
                <h1><b >Notificating in Gmail</b ></h1>
                <img src="/media/gmail-new-icon5198.jpg" style="width: 100%; height: 500px; object-fit: cover">
                <div class="box-info">
                    <div class="title-box">
                        <h2><b style="font-size: 28px;">DESCRIPTION</b></h2>
                    </div>
                    <div class="content-box">
                        <p>Sign up for free and start receiving your daily dose of cybersecurity news, insights and tips.</p>
                    </div>
                </div>
                <div class="box-info">
                    <div class="title-box">
                        <h2>
                            <b style="font-size: 28px;">Join for notications</b></h2>
                    </div>
                    <div class="content-box">
                        {% if msg %}
                            <p class="alert-msg">{{ msg }}</p>
                        {% endif %}
                        <form method="post" style="padding: 20px">
                            {% csrf_token %}
                            <p>Sign up for free and start receiving your daily dose of cybersecurity news, insights and tips.</p>
                            <input type="email" name="email_notification" placeholder="Your e-mail address">
                            <button type="submit" class="btn btn-one"><b>Make notification with Gmail</b></button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="box-info">
                    <div class="title-box">
                        <h2><b style="font-size: 28px;">Method Informations</b></h2>
                    </div>
                    <div class="content-box">
                        <p>Service: Telegram</p>
                        <p>Published: 2024-10-10</p>
                        <p>Updated: 2024-10-10</p>
                        <button class="btn btn-one"><b>Follow News Now</b></button>
                    </div>
                </div>
                <br>
                <div class="box-info">
                    <div class="title-box">
                        <h2><b style="font-size: 28px;">Asking for information</b></h2>
                    </div>
                    <div class="content-box">
                        <form method="post">
                            {% csrf_token %}
                            <input type="text" name="your_name" placeholder="Your Name"><br>
                            <input type="text" name="email_address" placeholder="Email Address"><br>
                            <input type="text" name="phone_number" placeholder="Phone Number"><br>
                            <textarea name="message" placeholder="Message" rows="5"></textarea><br>
                            <button class="btn btn-one" style="width: 100%"><b>Sent</b></button>
                        </form>
                    </div>
                </div>
                <div class="box-info">
                    <div class="title-box">
                        <h2><b style="font-size: 28px;">Another Methods</b></h2>
                    </div>
                    <div class="content-box">
                        <div class="card mb-3" style="max-width: 540px; border: none; background-color: lightgray !important;">
                          <div class="row g-0">
                            <div class="col-md-4">
                              <img src="/media/telegram_logo.jpg" class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="col-md-8">
                            <div class="card-body">
                                <h3 class="card-title1">
                                    <a href="{% url 'app:tele_noti' %}">Telegram
                                    </a>
                                </h3>
                                <p class="card-text">"How to receive notifications via Telegram whenever a new CVE is updated."</p>
                                <a href="{% url 'app:tele_noti' %}">
                                    <button class="btn btn-one"><b>READ MORE</b></button>
                                </a>
                              </div>
                            </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {#  fontansersome  #}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    {#  bootstrap  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <link rel="icon" type="image/x-icon" href="/media/CVE.jpg">
    <title>
    {% block title %}

    {% endblock %}
    </title>
    
    {#Cần chỉnh CSS#}
    <style>
        <!--Body-->
        body{
            font-family: 'Poppins', sans-serif;
            font-size: 16px;
            line-height: 24px;
            font-weight: 400;
            color: white;
         }
    
        <!--Link-->
   
        <!--social-->
        .button-container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 500%;
        }

        .glass-btn {
        width: 60px;
        height: 60px;
        background-color: #fafafa;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 7px;
        margin-left: 1em;
        margin-right: 1em;  
        cursor: pointer;
        transition: all 0.3s;

        &.blue-btn {
            -webkit-box-shadow: 0px 20px 20px -17px rgba(0, 111, 255, 0.53);
            -moz-box-shadow: 0px 20px 20px -17px rgba(0, 111, 255, 0.53);
            box-shadow: 0px 20px 20px -17px rgba(0, 111, 255, 0.53);

            &:hover {
            -webkit-box-shadow: 0px 20px 35px -16px rgba(0, 111, 255, 0.65);
            -moz-box-shadow: 0px 20px 35px -16px rgba(0, 111, 255, 0.65);
            box-shadow: 0px 20px 35px -16px rgba(0, 111, 255, 0.65);      
            }

            .content {
            font-size: 4em;
            font-family: "Roboto", sans-serif;
            background: linear-gradient(to right, #006fff, #00acff 70%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-shadow: 0px 10px 37px rgba(0, 111, 255, 0.8);
            }
        }

        &.red-btn {
            -webkit-box-shadow: 0px 20px 20px -17px rgba(255, 16, 39, 0.5);
            -moz-box-shadow: 0px 20px 20px -17px rgba(255, 16, 39, 0.5);
            box-shadow: 0px 20px 20px -17px rgba(255, 16, 39, 0.5);

            &:hover {
            -webkit-box-shadow: 0px 20px 35px -16px rgba(255, 16, 39, 0.57);
            -moz-box-shadow: 0px 20px 35px -16px rgba(255, 16, 39, 0.57);
            box-shadow: 0px 20px 35px -16px rgba(255, 16, 39, 0.57);      
            }

            .content {
            font-size: 4em;
            font-family: "Roboto", sans-serif;
            background: linear-gradient(to right, #ff1027, #ff4f06 70%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-shadow: 0px 10px 37px rgba(255, 16, 39, 0.6);
            }
        }

        &:hover {
            background-color: darken(#fafafa, 2%);    
            transform: translateY(-5px);
            transition: all 0.3s;
        }
        }

        @media screen and (min-width: 1600px) {
            ul.example1 {
              display: none;
            }
          }

        {% block css %}

        {% endblock %}
       
    </style>
</head>

{#  Thêm logic django  vào phần profile#}
<body>
{#  Chỉnh lại style  #}
<!--https://getbootstrap.com/docs/5.3/components/navbar/-->
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color:black; padding:15px;">
    <div class="container">
        <a class="navbar-brand" href="/"><b>CVE'S DAILY ALERT</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav example1">
                   
                    {% if user.is_superuser %}
                    <li content="nav-item">
                        <a class="nav-link" href= "http://127.0.0.1:8000/admin/" ><b>ADMIN</b></a>
                       
                    </li>
                    <li content="nav-item">
                        <a class="nav-link" href="{% url 'app:create_affected' %}"><b>Create Affected</b></a>
                    </li>
                    <li content="nav-item">
                        <a class="nav-link" href="{% url 'app:create_cve' %}"><b>Create CVE</b></a>
                       
                    </li>
                    {% endif %}
                </ul>
                <!--ms-md-auto chia navbar 2 phia-->
                <ul class="navbar-nav ms-md-auto">
                    {% if user.is_authenticated %}
                        <li content="nav-item">
                            <a class="nav-link" href="{% url 'accounts:profile' %}"><b><i class="fa-solid fa-user"></i> My Account:  {{ user.username }} </b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="right: -40px;" href="{% url 'accounts:log_out' %}"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fa-solid fa-right-to-bracket"></i> Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:sign_up' %}"><i class="fa-solid fa-user-plus"></i> Sign Up</a>
                        </li>
                    {% endif %}
                </ul>    
      </div>
    </div>
  </nav>
{% block content %}

{% endblock %}

<br>
<footer style="background-color: black; color: white;">
    <div class="row" style="padding: 30px">
        <div class="col">
            <h3>QUICK LINKS</h3>
            <p>Go fast to your destination</p>
            <a href="{% url 'app:home' %}"><p style="color: dodgerblue" >Home</p></a>
            <a href="{% url 'app:list_cves' page=1 %}" ><p style="color: dodgerblue" >Finding</p></a>
            <a {% if user.is_authenticated %} href="{% url 'accounts:profile' %}" {% else %}href="{% url 'accounts:login' %}" {% endif %}><p style="color: dodgerblue" >Profile</p></a> 
        </div>
        <div class="col icon-social" style="width: 80%" >
            <h3 style="margin-left:80px; margin-bottom:20px">ABOUT</h3>
            <div class="row">
                <div class="glass-btn blue-btn">
                    <!--<div class="content">
                      h
                    </div> -->
                    <a href="https://www.facebook.com/profile.php?id=100088244351596"><img src="/media/Facebook_logo_(square).png" alt="facebook" style="width: 4em; height:4em;"></a>
                  </div>
                
                  <div class="glass-btn red-btn">
                    <!-- <div class="content">
                      e
                    </div> -->
                    <a href="https://www.instagram.com/daily_cve_alert?fbclid=IwAR1QpxhZaR_wnf5HqTA2mB_v1WpHZPNdA5HtfX1aNbYDmdnYoBxOcI0W-5I"><img src="/media/Instagram_icon.png" alt="facebook" style="width: 4em; height:4em;"></a>
                  </div>
                  
                  <div class="glass-btn blue-btn">
                    <!-- <div class="content">
                      y
                    </div> -->
                    <a href="https://twitter.com/CveDailyAlert?fbclid=IwAR0Sq2jk2gQs_pO3M4T18g7YFnKPlriPPuZVn4Uo9sDSIGjGRtkIScP26HY"><img src="/media/new-twitter-logo-x-2023-twitter-x-logo-vector-download_691560-10795.png" alt="facebook" style="width: 5em; height:5em;"></a>
                  </div>
            </div>
        </div>
        <div class="col">
            <h3>FOR DEV OWNER</h3>
            <p>We value our CVE listings and are committed to providing support and the latest vulnerabilities based on
                the technologies our users follow.</p>
            <h3>BECOME OUR PARTNER</h3>
            <p>Interested in becoming our partner? Contact us here</p>
            <a href="mailto:CveDailyAlert@gmail.com"><p><b style="color: white">Email: CveDailyAlert@gmail.com</b></p>
            </a>
            <p><b>Phone number: 1900010000</b></p>
        </div>
    </div>
</footer>
</body>
</html>