CVEAlert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('account/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import get_home, get_list_CVE,get_detail_cves,get_tele_notifi,get_gmail_notifi,create_cve_view,create_affect_view

app_name = 'app'

urlpatterns = [
    path('', get_home,name='home'),
    path('list-cve/<int:page>/', get_list_CVE,name='list_cves'),
    path('detail-cve/<int:pk>', get_detail_cves, name='detail_cves'),
    path('create-cve/', create_cve_view, name = 'create_cve'),
    path('create-affected/', create_affect_view, name = 'create_affected'),
    path('telegram-notification/', get_tele_notifi, name='tele_noti'),
	path('gmail-notification/', get_gmail_notifi, name='gmail_noti')
]

firstapp/models.py
from django.db import models
from accounts.models import User

class CVE(models.Model):
    cve_id = models.CharField(max_length=255, default="")
    year = models.CharField(max_length=255, default="")
    data_version = models.CharField(max_length=255, default="")
    data_type = models.CharField(max_length=255, default="")
    date_reserved = models.CharField(max_length=255, default="", null = True)
    date_publish = models.CharField(max_length=255, default="", null = True)
    date_update = models.CharField(max_length=255, default="", null = True)
    assigner_Org_Id = models.CharField(max_length=255, default="", null = True)
    provider_Metadata = models.CharField(max_length=255, default="", null = True)

    def __str__(self):
        return self.cve_id
    
class Descriptions(models.Model):
    con = models.ForeignKey(CVE, on_delete=models.CASCADE, related_name='description_cves', blank=True, default=None)
    value = models.CharField(max_length=9000, default="", null = True)

    def __str__(self):
        return self.value
    
class Solutions(models.Model):
    con = models.ForeignKey(CVE, on_delete=models.CASCADE, related_name='solutions_cves', blank=True, default=None)
    value = models.CharField(max_length=9000, default="", null = True)

    def __str__(self):
        return self.value
    
class Versions(models.Model):
    version = models.CharField(max_length=3000, default="", null = True)
    status = models.CharField(max_length=255, default="", null = True)

    def __str__(self):
        return self.version
    
class Products(models.Model):
    name = models.CharField(max_length=3000, default="", null = True)

    def __str__(self):
        return self.name
    
class Vendors(models.Model):
    name = models.CharField(max_length=3000, default="", null = True)

    def __str__(self):
        return self.name
    
class Products_Versions(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product_version', blank=True, default=None)
    version = models.ForeignKey(Versions, on_delete=models.CASCADE, related_name='version_product', blank=True, default=None)
    
    def __str__(self):
        return self.product
    
class Affected(models.Model):
    con = models.ForeignKey(CVE, on_delete=models.CASCADE, related_name='affected_cves', blank=True, default=None)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product_vendor', blank=True, default=None)
    vendor = models.ForeignKey(Vendors, on_delete=models.CASCADE, related_name='vendor_product', blank=True, default=None)

    def __str__(self):
        return self.product
    
class References(models.Model):
    con = models.ForeignKey(CVE, on_delete=models.CASCADE, related_name='references_cves', blank=True, default=None)
    url = models.CharField(max_length=3000, default="", null = True)

    def __str__(self):
        return self.url
    
class CvssV20(models.Model):
    version = models.CharField(max_length=255, default="", null = True)
    vector_string = models.CharField(max_length=300, default="", null = True)
    base_score = models.FloatField(default="", null = True)

    def __str__(self):
        return self.version
    
class CvssV30(models.Model):
    version = models.CharField(max_length=255, default="", null = True)
    vector_string = models.CharField(max_length=300, default="", null = True)
    base_score = models.FloatField(default="", null = True)
    base_severity = models.CharField(max_length=255, default="", null = True)

    def __str__(self):
        return self.version
    
class CvssV31(models.Model):
    version = models.CharField(max_length=255, default="", null = True)
    vector_string = models.CharField(max_length=400, default="", null = True)
    base_score = models.FloatField(default="", null = True)
    base_severity = models.CharField(max_length=255, default="", null = True)

    def __str__(self):
        return self.version
    
class Metric(models.Model):
    con = models.ForeignKey(CVE, on_delete=models.CASCADE, related_name='metric_cve', blank=True, default=None)
    cvssv20 = models.ForeignKey(CvssV20, on_delete=models.CASCADE, related_name='metric_cvss_v20', blank=True, default=None)
    cvssv30 = models.ForeignKey(CvssV30, on_delete=models.CASCADE, related_name='metric_cvss_v30', blank=True, default=None)
    cvssv31 = models.ForeignKey(CvssV31, on_delete=models.CASCADE, related_name='metric_cvss_v31', blank=True, default=None)
    
    def __str__(self):
        return self.con
    
class Follow_Affected(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follow_user', blank=True, default=None)
    affected = models.ForeignKey(Affected, on_delete=models.CASCADE, related_name='follow_affected', blank=True, default=None)

    def __str__(self):
        return self.user
# Create your models here.

firstapp/forms.py
from django import forms
from ckeditor.fields import RichTextField
from .models import CVE,Affected

class CVEform(forms.ModelForm):
    class Meta:
        model = CVE
        fields = '__all__'

        widgets = {
            'description' : RichTextField(config_name='default')
        }
class AffectedForm(forms.ModelForm):
    class Meta:
        model = Affected
        fields = '__all__'

firstapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage , PageNotAnInteger
from .models import CVE , Affected , References , Metric , CvssV31 , Products , Vendors , Descriptions , Solutions , Products_Versions , Follow_Affected 
from accounts.models import NotiUser
from .forms import CVEform,AffectedForm
from django.db.models import F, DateTimeField , ExpressionWrapper
from django.db.models.functions import Cast
# Create your views here.
def get_home(request):
    listCVE = CVE.objects.all().order_by('-date_publish')[:3]
    cve_ids = [cve.id for cve in listCVE] 
    affected = Affected.objects.filter(con_id__in=cve_ids) 
    products = [a.product for a in affected]
    vendors = [a.vendor for a in affected]
    if request.method == 'POST': 
            id_cve= request.POST['id_cve']
            listCVE = CVE.objects.filter(cve_id__contains=id_cve)[:12]
    context = {
        'listCVE': listCVE,
        'products': products,
        'vendors': vendors,
        'affected': affected,
    }
    return render(request, 'home.html', context=context)

def get_list_CVE(request, page):
    listCVE= CVE.objects.all().order_by('date_publish')
    year = CVE.objects.values_list('year',flat=True)
    unique_Year = set(year)
    unique_year_List = list(unique_Year)
    unique_year_List.sort()
    if request.method == 'POST':
        selected_years = request.POST.getlist('filter_year')
        if selected_years:
            listCVE = CVE.objects.filter(year__in=selected_years)
    if request.method == 'POST':  
        if 'search_focus' in request.POST:
            id_cve= request.POST['search_focus']
            listCVE = CVE.objects.filter(cve_id__contains=id_cve)
    per_page = request.GET.get("per_page", 10)
    paginator = Paginator(listCVE, per_page)
    page_obj = paginator.get_page(page)

    cve_ids = [cve.id for cve in page_obj]

    affected = Affected.objects.filter(con_id__in=cve_ids)
    products = {}
    vendors = {}
    for a in affected:
        if a.con_id in products:
            products[a.con_id].append(a.product)
            vendors[a.con_id].append(a.vendor)
        else:
            products[a.con_id] = [a.product]
            vendors[a.con_id] = [a.vendor]
    page_obj.affected = affected
    if request.method == 'POST' and 'search_focus' in request.POST and 'products' in request.POST:
             product_Name = request.POST['search_focus']
             affected = Affected.objects.filter(product__in = product_Name)
    elif request.method == 'POST' and 'search_focus' in request.POST and 'vendors' in request.POST:
             vendors_Name = request.POST['search_focus']
             affected = Affected.objects.filter(vendor__in=vendors_Name)   
    page_obj.affected = affected
    # print(unique_year_List)
    context={
        "page": {
			'prev': page_obj.number - 1 if page_obj.number - 1 > 0 else 1,
			'current': page_obj.number,
			'next': page_obj.number + 1 if page_obj.number + 1 < paginator.num_pages else paginator.num_pages,
		},
        'len_page': paginator.num_pages,
        'paginator': paginator,
        'page_obj' : page_obj,
        'products' : products,
        'vendors' : vendors,
        'affected' : affected,
        'unique_year' : unique_year_List
        

    }

    # print(listCVE)
    return render(request, 'firstapp/list_cves.html', context=context)   

def get_detail_cves(request, pk):
    detail_cve = CVE.objects.get(pk=pk)
    affected = Affected.objects.filter(con_id=detail_cve.id)
    
    products = [a.product for a in affected]
    products_versions = Products_Versions.objects.filter(product__in=products)
    versions = [p.version for p in products_versions]
    vendors = [a.vendor for a in affected]
     
    try :
        metric = Metric.objects.filter(con_id=detail_cve.id)
    except :
        metric = None
    cvssv31 = [m.cvssv31 for m in metric]
     
    try:
        solutions = Solutions.objects.get(pk=pk)
    except Solutions.DoesNotExist:
        solutions = None

    try:
        descriptions = Descriptions.objects.get(pk=pk)
    except Descriptions.DoesNotExist:
        descriptions = None
    try:
        refrences = References.objects.filter(con_id=pk)
    except References.DoesNotExist:
         refrences = None

    if request.method == 'POST':
        affect_id = request.POST['follow_affect']
        if affect_id == 'null':
             msg = 'need affected info !'
        else:
            try:
                  check = Follow_Affected.objects.get(user=request,affect_id=affect_id)
            except:
                 check = None
            
            if check:
                 msg = 'You had follow this Affected'
            else:
                 follow_affect = Follow_Affected.objects.create(user=request.user, affect_id=affect_id)
                 follow_affect.save
                 msg = "u have tracked successfully!"
    else:
         msg = ""
       
    context = {
         'detail_cve': detail_cve,
         'products' : products,
         'versions' : versions,
         'vendors' : vendors,
         'affected': affected,
         'products_versions' : products_versions,
         'metric' : metric,
         'solutions' : solutions,
         'descriptions' : descriptions,
         'refrences' : refrences,
         'cvssv31' : cvssv31,
         'alert-msg' : msg 

    }

    return render(request, 'firstapp/detail_cve.html' , context=context)

def create_cve_view(request):
    form =CVEform()
    if request.method == 'POST':
        form = CVEform(request.POST or None, request.FILES)
        if form.is_valid():
            data  = form.save(commit=True)
        return HttpResponseRedirect(reverse('app:home'))
    context = {
         'form':form
    }
    return render(request, 'firstapp/create_cves.html', context=context)

def create_affect_view(request):
    form = AffectedForm()
    if request.method == 'POST':
        form = AffectedForm(request.POST)
        if form.is_valid():
            data = form.save(commit=True)
            return HttpResponseRedirect(reverse('app:home'))
    context ={
          'form':form
        }
    return render(request, 'firstapp/create_affected.html', context=context)

def get_tele_notifi(request):
	return render(request, 'telegram_notifi.html')


def get_gmail_notifi(request):	
	return render(request, 'gmail_notifi.html')

templates/firstapp/create_affected.html
{% extends 'navbar.html' %}

{% block css %}
    a {
    text-decoration: none;
    color: black;
    }
    input, textarea, select {
    width: 100%;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 10px;
    }

    /*=Create Affected=*/
    .btn {
        line-height: 20px;
        height: 50px;
        text-align: center;
        text-style:bold
        cursor: pointer;
        background-color:dodgerblue;
      }
      .btn-one {
        color: white;
        transition: all 0.5s;
        position: relative;
      }
      .btn-one span {
        transition: all 0.5s;
      }
      .btn-one::before {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 2;
        opacity: 0;
        transition: all 1s;
        border-top-width: 1px;
        border-bottom-width: 1px;
        border-top-style: solid;
        border-bottom-style: solid;
        border-top-color: dodgerblue;
        border-bottom-color: dodgerblue;
        transform: scale(0.1, 1);
        
      }
      .btn-one:hover span {
        letter-spacing: 2px;
      }
      .btn-one:hover::before {
        opacity: 1; 
        transform: scale(1, 1); 
      }
      .btn-one::after {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        transition: all 0.3s;
        background-color: rgba(255,255,255,0.1);
      }
      .btn-one:hover::after {
        opacity: 0; 
        transform: scale(0.1, 1);
      }
{% endblock %}

{% block title %}
    Create Affected
{% endblock %}

{% block content %}
    <div class="container" style="margin:80px">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-8">
                <h2><b style="color: dodgerblue">CREATE</b><b> AFFECTED</b></h2>
               {% comment %} <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="cve_id">CVE ID: </label>
                    <input type="text" name="cve_id" maxlength="40" id="cve_id">
                    <label for="Product">Product: </label>
                    <input type="text" name="Product" maxlength="50" id="Product">
                    <label for="Vendor">Vendor:</label>
                    <input type="text" name="Vendor" maxlength="20" id="Vendor" >
                    <button type="submit" class="btn btn-one"><b>Create Affected!</b></button>
                </form>  {% endcomment %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-one"><b>Create Affected</b></button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/firstapp/detail_cve.html
{% extends 'navbar.html' %}


{% block css %}
    a {
    text-decoration: none;
    color: black;
    }
    input, textarea {
    width: 100%;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 10px;
    }
    .title-box > * {
    padding: 10px;
    background-color: black !important;
    color: white !important;
    border-top-right-radius: 10px !important;
    border-top-left-radius: 10px !important;
    margin: 0;
    }
    .box-info {
        margin-bottom: 20px;
        margin-top: 20px;
    }
    .content-box {
    background-color: lightgray !important;
    border-bottom-right-radius: 10px;
    border-bottom-left-radius: 10px;
    margin: 0;
    padding: 10px;
    }
    .base-score {
    background-color: black !important;
    color: white !important;
    padding: 10px;
    border-radius: 10px;
    }
    .alert-msg {
        background-color: lightgreen;
        color: white;
        padding: 10px;
        border-radius: 5px;
        border-color: red;
    }

    /*=READ NOW=*/
.btn {
    line-height: 20px;
    height: 50px;
    text-align: center;
    text-style:bold
    cursor: pointer;
    background-color:black;
  }
  .btn-one {
    color: white;
    transition: all 0.5s;
    position: relative;
  }
  .btn-one span {
    transition: all 0.5s;
  }
  .btn-one::before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 2;
    opacity: 0;
    transition: all 1s;
    border-top-width: 1px;
    border-bottom-width: 1px;
    border-top-style: solid;
    border-bottom-style: solid;
    border-top-color: black;
    border-bottom-color: black;
    transform: scale(0.1, 1);
    
  }
  .btn-one:hover span {
    letter-spacing: 2px;
  }
  .btn-one:hover::before {
    opacity: 1; 
    transform: scale(1, 1); 
  }
  .btn-one::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    transition: all 0.3s;
    background-color: rgba(255,255,255,0.1);
  }
  .btn-one:hover::after {
    opacity: 0; 
    transform: scale(0.1, 1);
  }
  /*=URL=*/
.url{
    a {
        color: black;
      position: relative;
      text-decoration: none;
    }
    
    a::before {
      content: '';
      position: absolute;
      width: 100%;
      height: 2px;
      border-radius: 4px;
      background-color: #18272F;
      bottom: 0;
      left: 0;
      transform-origin: right;
      transform: scaleX(0);
      transition: transform .3s ease-in-out;
    }
}

a:hover::before {
  transform-origin: left;
  transform: scaleX(1);
}

/*=Link list=*/
  .list{
      a {
          box-shadow: inset 0 0 0 0 black;
          color: black;
            padding: 0 .25rem;
            margin: 0 -.25rem;
            left:10%;
            border-radius: 5px;
          transition: color .5s ease-in-out, box-shadow .5s ease-in-out;
        }
        a:hover {
          color: white;
          box-shadow: inset 200px 0 0 0 black;;
        }
        
        /* Presentational styles */
        a {
          color: black;
          font-size: 19px;
          font-weight: 500;
          line-height: 0;
          text-decoration: none;
        }
  }



  /*=arrow=*/
.arrow {
    position: absolute;
    top: 19%;
    left: 14%;
    transform: translate(-50%, -50%);
    transform: rotate(90deg);
    cursor: pointer;
}

.arrow span {
    display: block;
    width: 1vw;
    height: 1vw;
    border-bottom: 5px solid black;
    border-right: 5px solid black;
    transform: rotate(45deg);
    margin: -10px;
    animation: animate 2s infinite;
}

.arrow span:nth-child(2) {
    animation-delay: -0.2s;
}

.arrow span:nth-child(3) {
    animation-delay: -0.4s;
}

@keyframes animate {
    0% {
        opacity: 0;
        transform: rotate(45deg) translate(-20px, -20px);
    }
    50% {
        opacity: 1;
    }
    100% {
        opacity: 0;
        transform: rotate(45deg) translate(20px, 20px);
    }
}



{% endblock %}


{% block title %}
    Detail CVEs
{% endblock %}


{% block content %}
{# Thêm logic để hiện thị các trường của CVE #}
<div class="container" style="margin-top: 100px; margin-bottom: 200px">
    <p class="list"><a href={% url 'app:list_cves' page=1 %}>Explore CVE list</a></p>
    <div class="arrow" onclick="goBack()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <div class="row">
        <div class="col-8">
            <h1><b>{{ detail_cve.cve_id }}</b></h1>
            <div class="box-info">
                <div class="title-box">
                    <h2><b style="font-size: 28px;">DESCRIPTION</b></h2>
                </div>
                <div class="content-box">
                    <p>{{ descriptions.value }}</p>
                </div>
            </div>
            <div class="box-info">
                <div class="title-box">
                    <h2><b style="font-size: 28px;">Vulnerable products, Vendor</b></h2>
                </div>
                <div class="content-box">
                        {% for a in affected %} 
                            {% if a.con_id == detail_cve.id %}
                                <p><b>- Product name:</b> {{ a.product.name }}</p>
                                <p><b>- Vendor name: </b>{{ a.vendor.name }}</p>
                            {% endif %}
                            {% for p in products_versions %} 
                                {% if p.product_id == a.product.id %}
                                    <p><b>+ Version:</b> {{ p.version.version }}</p>
                                {% endif %}
                            {% endfor %}
                </br>
                        {% endfor %}
                </div>
            </div>
            <div class="box-info">
                <div class="title-box">
                    <h2><b style="font-size: 28px;">Solution, References</b></h2>
                </div>
                <div class="content-box url">
                    <p><b>- Solution: </b>{{ solutions.value }}</p>
                    {% for r in refrences %}
                        {% if r.con_id == detail_cve.id %}
                        <b>+ URL:</b><a href="{{ r.url }}"> {{ r.url }}</a>
                </br>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="box-info">
                <p class="base-score"><b style="font-size: 20px;">BASE SCORE V3.1 </b>
                    {% for m in metric %}
                        {% if m.con_id == detail_cve.id %}
                            <span style="float: right">{{ m.cvssv31.base_score }}</span>
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
        <div class="col-4">
            <div class="box-info">
                <div class="title-box">
                    <h2><b style="font-size: 28px;">CVE Informations</b></h2>
                </div>
                <div class="content-box">
                    <form method="post">
                        {% csrf_token %}
                            <p class="alert-msg">You have been follow this affect</p>
                        <p><b>CVE ID:</b> {{ detail_cve.cve_id }}</p>
                        <p><b>Published Date:</b> {{ detail_cve.date_publish }}</p>
                            <input name="follow_affect" value="null" style="display: none">
                            <input name="follow_affect" value="null" style="display: none">
                        <button class="btn btn-one"><b>Follow News Now</b></button>
                    </form>
                </div>
            </div>
            <br>
            <div class="box-info">
                <div class="title-box">
                    <h2><b style="font-size: 28px;">Asking for information</b></h2>
                </div>
                <div class="content-box">
                    <form method="post">
                        {% csrf_token %}
                        <input type="text" name="your_name" placeholder="Your Name"><br>
                        <input type="text" name="email_address" placeholder="Email Address"><br>
                        <input type="text" name="phone_number" placeholder="Phone Number"><br>
                        <textarea name="message" placeholder="Message" rows="5"></textarea><br>
                        <button class="btn btn-one" style="width: 100%"><b>Sent</b></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/firstapp/list_cves.html
{% extends 'navbar.html' %}

{% block css %}
    a {
    text-decoration: none;
    color: black;
    }
    .pagination {
        display: flex;
        align-items: center;
        justify-content: center;
    }
    /*=SEARCH BAR=*/

   

    /*=CARD TITLE=*/
    .card-title{
        a {
            box-shadow: inset 0 0 0 0 black;
            color: black;
              padding: 0 .25rem;
              margin: 0 -.25rem;
              border-radius: 5px;
            transition: color .5s ease-in-out, box-shadow .5s ease-in-out;
          }
          a:hover {
            color: white;
            box-shadow: inset 200px 0 0 0 black;;
          }
          
          /* Presentational styles */
          a {
            color: black;
            font-family: 'Poppins', sans-serif;
            font-size: 23px;
            font-weight: 600;
            line-height: 0;
            text-decoration: none;
          }
    }
    /*=READ NOW=*/
    .btn {
        line-height: 20px;
        height: 60px;
        text-align: center;
        width: 120px;
        cursor: pointer;
        background-color:black;
      }
      .btn-one {
        color: white;
        transition: all 0.5s;
        position: relative;
      }
      .btn-one span {
        transition: all 0.5s;
      }
      .btn-one::before {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 2;
        opacity: 0;
        transition: all 1s;
        border-top-width: 1px;
        border-bottom-width: 1px;
        border-top-style: solid;
        border-bottom-style: solid;
        border-top-color: black;
        border-bottom-color: black;
        transform: scale(0.1, 1);
        
      }
      .btn-one:hover span {
        letter-spacing: 2px;
      }
      .btn-one:hover::before {
        opacity: 1; 
        transform: scale(1, 1); 
      }
      .btn-one::after {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        transition: all 0.3s;
        background-color: rgba(255,255,255,0.1);
      }
      .btn-one:hover::after {
        opacity: 0; 
        transform: scale(0.1, 1);
      }
      

/*=PAGE=*/
.pagination-style-one a { 
    padding: 10px; 
    margin: 15px;
    background: black; 
    color: white; 
    border-radius: 80%; 
    box-shadow: 0px 5px 10px 5px rgba(0,0,0,.1);}
.pagination-style-one a.selected, 
.pagination-style-one a:hover, 
.pagination-style-one a:active, 
.pagination-style-one a:focus { 
    padding: 15px; 
    box-shadow: 0px 5px 10px 0px rgba(0,0,0,.5);
}

.custom-select {
    position: relative;
    width: 100%;
    height:40px;
    font-size:17px;
    text-align:center;
    background-color:white;
    color:black;
    border-radius:5px;
  }


{% endblock %}


{% block title %}
    List CVEs
{% endblock %}


{% block content %}
<div class="container">
    <div class="row" style="margin-top: 30px; margin-bottom: 30px;">
        <div class="col-3">
        </div>
        <div class="col-9">
            <form method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input name="search_focus" type="search" class="form-control" placeholder="Search CVE ID..."/>
                    <button type="submit" class="btn btn-one">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>

    </div>
    <div class="row" style="margin-top: 30px;">
        {# Hiển thị filter year#}
        <div class="col-3 " >
        </br>
    </br>
</br>
</br>
            <h3><b><u>FINDING METHODS</u></b></h3>
        </br>
            <h3>FIND BY: </h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                <input type="checkbox" id="product" name="product" value="product">
                <label for="product">Product</label><br>
                <input type="checkbox" id="vendor" name="vendor" value="vendor">
                <label for="vendor">Vendor</label><br>
                
            </br>
                <h3>PUBLISHED YEARS:</h3>
                <hr>
                {% comment %} {% for it in unique_year %}
                    <input type="checkbox" id="years" name="filter_year" value="{{ it }}">
                    <label for="years">{{ it }}</label><br>
                {% endfor %}  {% endcomment %}
                <select name="filter_year" class="custom-select">
                    {% for it in unique_year %}
                    <b> <option value="{{ it }}">{{ it }}</option></b>
                    {% endfor %}
                </select>
                <hr>
            </br>


                <button type="submit" class="btn btn-one" style="width:100%"><b>FIND</b></button>


            </form>
            
        </div>
        <div class="col-9 ">
            <h2 style="font-size: 35px; text-align:center"><b><u>List CVEs</u></b></h2>
          
            {% for cve in page_obj %}
        </br>
                <div class="col" >
                    <div class="card h-100" style="border-width:2px; border-color:black">
                        <div class="card-body">
                            <h3 class="card-title">
                                <a href="{% url 'app:detail_cves' pk=cve.pk %}">{{ cve.cve_id }}</a>
                            </h3>
                            <div class="card-body" style="padding: 30px;">
                                <p class="card-text">
                                    <b> Year:</b> "{{ cve.year }}"
                                </p>
                                <p class="card-text">
                                    <b> Publish Date: </b>"{{ cve.date_publish }}"
                                </p>
                                <p class="card-text">
                                    {% for a in page_obj.affected %}
                                        {% if a.con_id == cve.id %}
                                            <p class="card-text"><b> Product:</b> "{{ a.product.name }}"</p>
                                        {% endif %}
                                    {% endfor %}
                                </p>
                                 <a href="{% url 'app:detail_cves' pk=cve.pk %}" class="cta">
                                    <button class="btn btn-one"> <b style= "color: dodgerblue"> READ </b>NOW</button>
                                </a> 
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </br>
            <div class="pagination pagination-style-one m-t-20">
                <a href="{% url 'app:list_cves' page=page.prev %}">< Pre</a>
                <a style="color:white">Page {{ page.current }}  of {{ len_page }}</a>
                <a href="{% url 'app:list_cves' page=page.next %}">Next ></a>
              </div>
        </div>   
    </div>
</div>
{% endblock %}